# Generated by Django 4.2.11 on 2024-11-06 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projectmanager', '0002_project_department'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='enrollment_number',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AddField(
            model_name='project',
            name='student_avatar',
            field=models.ImageField(default='student_avatars/default.png', upload_to='student_avatars/'),
        ),
        migrations.AddField(
            model_name='project',
            name='student_email',
            field=models.EmailField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='project',
            name='student_github',
            field=models.URLField(default=''),
        ),
        migrations.AddField(
            model_name='project',
            name='student_linkedin',
            field=models.URLField(default=''),
        ),
        migrations.AddField(
            model_name='project',
            name='student_name',
            field=models.CharField(default='Anonymous', max_length=100),
        ),
    ]
