# Generated by Django 4.2.11 on 2024-11-11 01:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projectmanager', '0003_project_enrollment_number_project_student_avatar_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='video',
            field=models.FileField(default='project_videos/default.mp4', upload_to='project_videos/'),
        ),
    ]
